// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeBuilder.Server.Data;

#nullable disable

namespace PokeBuilder.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeBuilder.Server.Models.Game", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Key");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.GameDexEntry", b =>
                {
                    b.Property<string>("GameKey")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("DexNumber")
                        .HasColumnType("integer");

                    b.HasKey("GameKey", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("GameDex");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.GamePokemonInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ObtainMethods")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("GameKey", "PokemonId")
                        .IsUnique();

                    b.ToTable("GamePokemonInfo");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.Learnset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LearnMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("GameKey", "PokemonId", "LearnMethod");

                    b.ToTable("Learnsets");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.PokemonEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StatAttack")
                        .HasColumnType("integer");

                    b.Property<int>("StatDefense")
                        .HasColumnType("integer");

                    b.Property<int>("StatHp")
                        .HasColumnType("integer");

                    b.Property<int>("StatSpAttack")
                        .HasColumnType("integer");

                    b.Property<int>("StatSpDefense")
                        .HasColumnType("integer");

                    b.Property<int>("StatSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PokemonIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.GameDexEntry", b =>
                {
                    b.HasOne("PokeBuilder.Server.Models.Game", "Game")
                        .WithMany("DexEntries")
                        .HasForeignKey("GameKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBuilder.Server.Models.PokemonEntry", "Pokemon")
                        .WithMany("DexEntries")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.GamePokemonInfo", b =>
                {
                    b.HasOne("PokeBuilder.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBuilder.Server.Models.PokemonEntry", "Pokemon")
                        .WithMany("GameDetails")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.Learnset", b =>
                {
                    b.HasOne("PokeBuilder.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBuilder.Server.Models.PokemonEntry", "Pokemon")
                        .WithMany("Learnsets")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.Team", b =>
                {
                    b.HasOne("PokeBuilder.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.Game", b =>
                {
                    b.Navigation("DexEntries");
                });

            modelBuilder.Entity("PokeBuilder.Server.Models.PokemonEntry", b =>
                {
                    b.Navigation("DexEntries");

                    b.Navigation("GameDetails");

                    b.Navigation("Learnsets");
                });
#pragma warning restore 612, 618
        }
    }
}
